// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT email FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getId = `-- name: GetId :one
SELECT id from users
WHERE email = $1
`

func (q *Queries) GetId(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getId, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const gethash = `-- name: Gethash :one
SELECT hashed_password FROM users
WHERE email = $1
`

func (q *Queries) Gethash(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, gethash, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const upgradeToRedByID = `-- name: UpgradeToRedByID :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
    AND is_chirpy_red = FALSE
`

func (q *Queries) UpgradeToRedByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeToRedByID, id)
	return err
}
